### ISSUE TITLE
Con usuario sin registrar recibo codigo 200 (ok) pero no body

### ISSUE THREAD

**Issue by arejula27** [UNIZAR-30226-2021-02/backend#16]
**Describe the bug**
Al pedir login con un usuario sin registrar se recibe un codigo 200 pero no se recibe body

**To Reproduce**

1. Mandar petición login con aaa aaaa

**Expected behavior**
Recibir codigo de error

**Screenshots**
![WhatsApp Image 2021-03-14 at 22 59 47](https://user-images.githubusercontent.com/46299278/111135423-edfaaf00-857c-11eb-8213-4cd83a21ead6.jpeg)

**Comment by Merni27** [comment]
yata
