### ISSUE TITLE
error 417 en changeMyName

### ISSUE THREAD

**Issue by SergioCE** [UNIZAR-30226-2021-02/backend#55]
![github](https://user-images.githubusercontent.com/57458744/118362050-23784480-b58e-11eb-91ae-c029cf5632fc.png)

Los headers están bien y pongo un nombre random pero no lo cambia.

**Comment by arejula27** [comment]
en movil funciona, debe ser error de la web

**Comment by Merni27** [comment]
Sergio esa peti devuelve 417 si el nuevo nombre  es null o existe ya un usuario con ese nombre, así que tiene pinta de que mandais un null (o nos llega eso). Miralo a ver, yo lo estuve mirando y no hay mucho donde se nos pueda haber colado un error, es una petición bastante simple. Mucha suerte con eso <3
